http:
  address: ":8080"

postgres:
  url: "postgres://postgres:1111@localhost:5432/cryptocurrency"

coingecko:
  api_key: "CG-yMV1tsqrusdwqPmquZ94VNWC"
  base_url: "https://api.coingecko.com/api/v3"

cron:
  update_interval: "15s"